[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  NODE_VERSION = "12.11.1"
  NPM_VERSION = "6.11.1"
  YARN_VERSION = "1.19.0"
  YARN_FLAGS = "--no-ignore-optional"
